# Generated by Django 5.0.1 on 2024-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flip_time', models.DateTimeField(auto_now_add=True)),
                ('side', models.CharField(choices=[('head', 'head'), ('tail', 'tail')], max_length=5)),
            ],
        ),
    ]
