# Generated by Django 5.0.1 on 2024-02-12 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_item_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
